name: GHPages

on:
  workflow_dispatch: null
  push:
    branches: [main]

jobs:
  deploy-docs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install And Build
        run: |+
          npm install --legacy-peer-deps
          npm i -D playwright-chromium
          npm run build:gh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
